services:
  web:
    image: php:8.2-apache
    container_name: apache_php_book_ecommerce
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mariadb:10.4.32
    container_name: mariadb_book_ecommerce
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_book_ecommerce
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  # tomcat:
  #   image: tomcat:8.5.96
  #   container_name: tomcat
  #   ports:
  #     - "8081:8080"

volumes:
  db_data:
