services:
  web:
    build: .
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/PHP_Book_ECommerce
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet

  db:
    image: mariadb:10.4.32
    container_name: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: book_ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8081:80"
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
